version: "3.7"
services:
  user-database:
    restart: always
    container_name: "stat_dbs"
    image: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - stat_network

  user-stat:
    build: .
    depends_on:
      - user-database
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
      - .secret
    tty: true
    volumes:
      - ./app:/app
    stdin_open: true
    networks:
      - stat_network

networks:
  stat_network:
    name: stat_network