FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
COPY ./.env /.env
COPY ./requirements.txt /requirements.txt
WORKDIR /
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
EXPOSE ${APP_PORT}
CMD uvicorn postgres_app.main:app --host 0.0.0.0 --port ${APP_PORT}